"""Step 2: V20 four-class recognition of the stage-1 accepted IQ dataset."""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path

# Keep Matplotlib's font cache inside the delivery folder.  This avoids a
# cross-process lock in the user's shared C:\\Users\\...\\.matplotlib directory
# when the GUI/IDE also has a Python process running.
ROOT = Path(__file__).resolve().parent
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".matplotlib"))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix

from recognition_core import predict_v20_closed_set


KNOWN = ("2ASK", "2FSK", "BPSK", "16QAM")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="V20 closed-set recognition of V13 accepted IQ data")
    # ===== Software integration: edit these defaults when output paths/names change. =====
    parser.add_argument("--input", type=Path, default=ROOT / "software_output" / "stage1_accepted_known_iq.npz", help="accepted-IQ dataset generated by 01_extract_open_set_known_npz.py")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "software_output", help="directory for V20 result JSON/CSV/figures")
    parser.add_argument("--result-name", default="stage2_v20_result.json", help="V20 summary JSON name")
    # ==============================================================================
    parser.add_argument("--records-name", default="stage2_v20_group_records.csv")
    parser.add_argument("--matrix-name", default="stage2_v20_confusion_matrix.png")
    parser.add_argument("--model", type=Path, default=ROOT / "model" / "v20_closed_set_long_window_model.joblib")
    return parser.parse_args()


def draw_matrix(matrix: np.ndarray, path: Path) -> None:
    ratio = matrix / np.maximum(matrix.sum(axis=1, keepdims=True), 1)
    figure, axis = plt.subplots(figsize=(7.2, 6.1), dpi=160)
    image = axis.imshow(ratio, cmap="Blues", vmin=0.0, vmax=1.0)
    axis.set_xticks(range(4), KNOWN); axis.set_yticks(range(4), KNOWN)
    axis.set_xlabel("V20 closed-set prediction"); axis.set_ylabel("Actual known class")
    axis.set_title("V20 four-class confusion matrix")
    for row in range(4):
        for column in range(4):
            axis.text(column, row, "{:.1f}%\n({})".format(100 * ratio[row, column], matrix[row, column]), ha="center", va="center", color="white" if ratio[row, column] > .55 else "black")
    figure.colorbar(image, ax=axis, label="Row-normalized ratio")
    figure.tight_layout(); figure.savefig(path, bbox_inches="tight"); plt.close(figure)


def main() -> None:
    args = parse_args(); args.output_dir.mkdir(parents=True, exist_ok=True)
    with np.load(args.input, allow_pickle=False) as source:
        if "iq" not in source.files:
            raise KeyError("accepted dataset must contain an iq field")
        iq = np.asarray(source["iq"], dtype=np.float32)
        indices = np.asarray(source["source_block_indices"], dtype=np.int64) if "source_block_indices" in source.files else np.arange(len(iq))
        labels = np.asarray(source["labels"], dtype=np.int64) if "labels" in source.files else None
        names = np.asarray(source["class_names"]) if "class_names" in source.files else None
    result = predict_v20_closed_set(iq, args.model)
    group_size = int(result["group_size"]); used = int(result["used_blocks"])
    group_indices = indices[:used].reshape(-1, group_size)
    predicted_names = np.asarray([row["closed_set_label"] for row in result["records"]])
    records = []
    for group_id, source_indices in enumerate(group_indices):
        records.append({"group_id": int(group_id), "source_block_start": int(source_indices[0]), "source_block_end": int(source_indices[-1]), "v20_prediction": str(predicted_names[group_id])})
    record_path = args.output_dir / args.records_name
    with record_path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=records[0].keys() if records else ("group_id", "source_block_start", "source_block_end", "v20_prediction"))
        writer.writeheader(); writer.writerows(records)
    summary: dict[str, object] = {
        "input_accepted_dataset": str(args.input.resolve()), "model": str(args.model.resolve()),
        "group_size_blocks": group_size, "group_iq_points": group_size * 16384,
        "complete_group_count": int(len(records)), "dropped_tail_blocks": int(result["dropped_tail_blocks"]),
        "records": str(record_path.resolve()), "labels_used_for_inference": False,
    }
    # A matrix/accuracy can be generated only for a labelled test dataset.  The
    # labels are inspected after predictions and never influence V20 results.
    if labels is not None and names is not None and len(labels) == len(iq):
        actual_blocks = np.asarray([str(names[index]) for index in labels[:used]])
        actual_groups = actual_blocks.reshape(-1, group_size)
        valid = np.asarray([np.all(row == row[0]) and row[0] in KNOWN for row in actual_groups], dtype=bool)
        if np.any(valid):
            truth = np.asarray([KNOWN.index(row[0]) for row in actual_groups[valid]], dtype=np.int64)
            prediction = np.asarray([KNOWN.index(value) for value in predicted_names[valid]], dtype=np.int64)
            matrix = confusion_matrix(truth, prediction, labels=np.arange(4))
            matrix_path = args.output_dir / args.matrix_name
            draw_matrix(matrix, matrix_path)
            summary["labelled_homogeneous_known_group_count"] = int(np.sum(valid))
            summary["four_class_accuracy"] = float(np.mean(truth == prediction))
            summary["confusion_matrix"] = matrix.tolist()
            summary["confusion_matrix_plot"] = str(matrix_path.resolve())
    summary_path = args.output_dir / args.result_name
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print("V20 complete groups:", len(records))
    if "four_class_accuracy" in summary:
        print("V20 four-class accuracy: {:.4f}%".format(100 * float(summary["four_class_accuracy"])))
    print("V20 records:", record_path)
    print("V20 summary:", summary_path)


if __name__ == "__main__":
    main()
